$(document).ready(function(){
    $('#h').click(function(){
        $('#m1').hide();
        $('#m3').hide();
        $('#m2').hide();
        $('body').css('background-color','#ff7143');
        $('#about').show('slow');
    });
      $('#r').click(function(){
        $('#about').hide();
        $('#m2').hide();
        $('#m3').hide();
        $('body').css('background-color','#673AB7');
        $('#m1').show();
        $('#apane1').slideDown(1000).fadeIn(2000);
        $('#apane2').fadeIn(2000);
        $('#apane3').fadeIn(2000);
       
    });
    $('#p').click(function(){
        $('#about').hide();
        $('#m1').hide();
        $('#m3').hide();
        $('body').css('background-color','#EDE7F6');
        $('#m2').fadeIn(2000);
    });
    $('#c').click(function(){
        $('#about').hide();
        $('#m1').hide();
        $('#m2').hide();
        $('body').css('background-color','#CDDC39');
        $('#m3').show(2000);
    });
       $('.mr').click(function(){
        $('#about').hide();
        $('#m2').hide();
        $('#m3').hide();
        $('body').css('background-color','#673AB7');
        $('#m1').show();
        $('#apane1').slideDown(1000).fadeIn(2000);
        $('#apane2').fadeIn(2000);
        $('#apane3').fadeIn(2000);
		
    });
    $('.mw').click(function(){
        $('#about').hide();
        $('#m1').hide();
        $('#m3').hide();
        $('body').css('background-color','#EDE7F6');
          $('#m2').fadeIn(3000);
    });
    $('.ms').click(function(){
       $('#about').hide();
        $('#m2').hide();
        $('#m3').hide();
        $('body').css('background-color','#673AB7');
        $('#m1').show();
        $('#apane1').slideDown(1000).fadeIn(2000);
        $('#apane2').fadeIn(2000);
        $('#apane3').fadeIn(2000);
		
    });
    });